apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-hack-minecraft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-hack-minecraft
    spec:
      containers:
      - name: minecraft-server
        image: openhack/minecraft-server:1.0
        ports:
        - containerPort: 25565
          name: minecraft
        env:
        - name: "EULA"
          value: "TRUE"
        - name: "MOTD"
          value: "FROM YAML AKS"
      - name: sidecar
        image: yeyus/openhack-rcon-sidecar:latest
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PORT
          value: "25565"
        - name: HOST
          value: "localhost"
        - name: AZURE_CUSTOMER_ID
          valueFrom:
            configMapKeyRef:
              name: analytics-sidecar-config
              key: azure_customer_id
        - name: AZURE_SHARED_KEY
          valueFrom:
            configMapKeyRef:
              name: analytics-sidecar-config
              key: azure_shared_key
---
apiVersion: v1
kind: Service
metadata:
  name: azure-hack-minecraft-svc
spec:
  type: LoadBalancer
  ports:
  - port: 25565
  selector:
    app: azure-hack-minecraft
