apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-minecraft-scaler
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: azure-hack-minecraft
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 5
